# Generated by Django 2.2.28 on 2023-08-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_auto_20230807_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['-id']},
        ),
    ]
