# Generated by Django 2.2.28 on 2023-08-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20230810_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
    ]
